language: java

jdk:
  - oraclejdk8

services:
  - docker

sudo: required

install:
  - echo "maven install"
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ./mvnw test -B

script:
  - docker build -t superhao/spring-boot-in-docker .

after_success:
  - docker run --name spring-boot-in-docker-demo -d -p 8888:8080 superhao/spring-boot-in-docker
  - docker ps -a
  - curl localhost:8888/hello
  - docker stop spring-boot-in-docker-demo